dram:
  type: LPDDR5
  hardware_capacity: 68719476736  # 64GB in bytes
  hierarchy:
    bankgroup_bits: 2
    bank_bits: 2
    column_bits: 10
    row_bits: 17
  interface:
    DQ: 5
    prefetch_size: 256
  extensions:
    row_xor_interleaving: false

mapping:
  scheme: "CUSTOM"
  bit_mapping:
    # All direct mapping (no XOR)
    column: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
    bankgroup: [11, 10]
    bank: [13, 12]
    row: [30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14]